title: My First GitHub Page
author: Adam Humble
email: adam.r.humble@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my first GitHub page. I'm learning a lot about how this works.
theme: minima

# social links
twitter_username: adamthehumble # DO NOT include the @ character, or else the build will fail!
github_username:  adamhumble # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
